version: '3'

services:
  app:
    image: com.cherashev/candles:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TICKS_SOURCE_URL: ws://localhost:9989

  redis:
    image: redis:7-alpine
    restart: on-failure
    networks:
      - backend
    volumes:
      - redis-data:/data

networks:
  backend:

volumes:
  redis-data:
