---
candles:
  ticksSourceUrl: ${TICKS_SOURCE_URL:ws://localhost:9989}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

logging:
  level:
    root: INFO
    com.cherashev: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    enabled: true
